name: humanizer
description: A library to convert Dart values into human-friendly representations.
version: 3.0.1
repository: https://github.com/kentcb/humanizer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  decimal: ^3.0.0
  intl: ^0.20.2
  meta: ^1.3.0
  rational: ^2.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.1
